
import React from 'react';
import { TableConfig } from '../types';

interface FinancialTableProps {
  config: TableConfig;
}

const FinancialTable: React.FC<FinancialTableProps> = ({ config }) => {
  if (!config.rows || config.rows.length === 0) return null;

  return (
    <div className="w-full h-full flex flex-col bg-white dark:bg-slate-800 transition-colors duration-300">
      {/* Header */}
      <div className="px-6 py-5 border-b border-slate-200 dark:border-slate-700 bg-slate-50/50 dark:bg-slate-800/50 flex-shrink-0">
         <h3 className="text-lg font-bold text-slate-800 dark:text-white tracking-tight uppercase">
            {config.title}
         </h3>
         {config.description && <p className="text-sm text-slate-500 dark:text-slate-400 mt-1">{config.description}</p>}
      </div>
      
      {/* Scrollable Body */}
      <div className="flex-1 overflow-auto">
        <table className="w-full text-left border-collapse min-w-[600px]">
          <thead className="bg-white dark:bg-slate-800 sticky top-0 z-10 shadow-sm">
            <tr>
              {config.columns.map((col, idx) => (
                <th key={idx} className="px-6 py-4 text-xs font-bold text-slate-500 dark:text-slate-400 uppercase tracking-wider border-b border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-800">
                  {col}
                </th>
              ))}
            </tr>
          </thead>
          <tbody className="divide-y divide-slate-100 dark:divide-slate-700/50">
            {config.rows.map((row, rIdx) => (
              <tr key={rIdx} className="hover:bg-blue-50/30 dark:hover:bg-blue-900/10 transition-colors group">
                {config.columns.map((col, cIdx) => {
                    const value = row[col];
                    const isNumber = typeof value === 'number' || (typeof value === 'string' && /^[0-9$.,%\-()]+$/.test(value));
                    return (
                        <td key={cIdx} className={`px-6 py-3.5 text-sm text-slate-700 dark:text-slate-300
                            ${cIdx === 0 ? 'font-semibold text-slate-900 dark:text-slate-100' : ''}
                            ${isNumber ? 'font-mono text-right' : ''}
                        `}>
                            {value}
                        </td>
                    );
                })}
              </tr>
            ))}
          </tbody>
        </table>
      </div>
      <div className="px-6 py-3 border-t border-slate-200 dark:border-slate-700 bg-slate-50 dark:bg-slate-900/50 text-[10px] text-slate-400 text-right flex-shrink-0">
        Generated by FinPartner AI • Verified Output
      </div>
    </div>
  );
};

export default FinancialTable;
